version: '3.2'

# volumes:
#   data:

services:

  backend:
    image: creathus/backend-agenda-contatos:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  db:
    image: docker.io/mariadb:10.5.9-focal
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    labels:
      - environment:development
#    volumes:
#      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0-fpm-alpine
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1