version: '3.2'

# volumes:
#   data:

services:

  backend:
    image: creathus/backend-agenda-contatos:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  db:
    image: docker.io/mariadb:10.5.9-focal
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev_agenda_contatos
    labels:
      - environment:development
#    volumes:
#      - data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8888:8080