version: '3.2'

# volumes:
#   data:

services:

  backend:
    image: creathus/backend-agenda-contatos:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: backend
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_NAME=dev_agenda_contatos
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
      - DB_CHARSET=utf8
      - DB_TEST_NAME=test_agenda_contatos
      - ENV=dev

  db:
    image: docker.io/mariadb:10.5.9-focal
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev_agenda_contatos
    labels:
      - environment:development
#    volumes:
#      - data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8888:8080