"""
Django settings for AgendaContatosBackend project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uedno6x)9^!!8%gvhf46e_a!%-$qr!li%gr3mo%azji22=7+3d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'drf_spectacular',
    'AgendaContatosBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True  # If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    'http://localhost:5000'
]

ROOT_URLCONF = 'AgendaContatosBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    )
}

WSGI_APPLICATION = 'AgendaContatosBackend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
        'CHARSET': os.environ['DB_CHARSET'],
        'TEST': {
            'NAME': os.environ['DB_TEST_NAME'],
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    # # A regex specifying the common denominator for all operation paths. If
    # # SCHEMA_PATH_PREFIX is set to None, drf-spectacular will attempt to estimate
    # # a common prefix. use '' to disable.
    # # Mainly used for tag extraction, where paths like '/api/v1/albums' with
    # # a SCHEMA_PATH_PREFIX regex '/api/v[0-9]' would yield the tag 'albums'.
    # 'SCHEMA_PATH_PREFIX': None,
    # # Remove matching SCHEMA_PATH_PREFIX from operation path. Usually used in
    # # conjunction with appended prefixes in SERVERS.
    # 'SCHEMA_PATH_PREFIX_TRIM': False,

    # 'DEFAULT_GENERATOR_CLASS': 'drf_spectacular.generators.SchemaGenerator',

    # # Schema generation parameters to influence how components are constructed.
    # # Some schema features might not translate well to your target.
    # # Demultiplexing/modifying components might help alleviate those issues.
    # #
    # # Create separate components for PATCH endpoints (without required list)
    # 'COMPONENT_SPLIT_PATCH': True,
    # # Split components into request and response parts where appropriate
    # 'COMPONENT_SPLIT_REQUEST': False,
    # # Aid client generator targets that have trouble with read-only properties.
    # 'COMPONENT_NO_READ_ONLY_REQUIRED': False,

    # # Configuration for serving a schema subset with SpectacularAPIView
    # 'SERVE_URLCONF': None,
    # # complete public schema or a subset based on the requesting user
    # 'SERVE_PUBLIC': True,
    # # include schema enpoint into schema
    # 'SERVE_INCLUDE_SCHEMA': True,
    # # list of authentication/permission classes for spectacular's views.
    # 'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    # # None will default to DRF's AUTHENTICATION_CLASSES
    # 'SERVE_AUTHENTICATION': None,

    # # Dictionary of configurations to pass to the SwaggerUI({ ... })
    # # https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
    # 'SWAGGER_UI_SETTINGS': {
    #     'deepLinking': True,
    # },
    # 'SWAGGER_UI_DIST': '//unpkg.com/swagger-ui-dist@3.44.0',
    # 'SWAGGER_UI_FAVICON_HREF': '//unpkg.com/swagger-ui-dist@3.44.0/favicon-32x32.png',

    # # Append OpenAPI objects to path and components in addition to the generated objects
    # 'APPEND_PATHS': {},
    # 'APPEND_COMPONENTS': {},

    # # DISCOURAGED - please don't use this anymore as it has tricky implications that
    # # are hard to get right. For authentication, OpenApiAuthenticationExtension are
    # # strongly preferred because they are more robust and easy to write.
    # # However if used, the list of methods is appended to every endpoint in the schema!
    # 'SECURITY': [],

    # # Postprocessing functions that run at the end of schema generation.
    # # must satisfy interface result = hook(generator, request, public, result)
    # 'POSTPROCESSING_HOOKS': [
    #     'drf_spectacular.hooks.postprocess_schema_enums'
    # ],

    # # Preprocessing functions that run before schema generation.
    # # must satisfy interface result = hook(endpoints=result) where result
    # # is a list of Tuples (path, path_regex, method, callback).
    # # Example: 'drf_spectacular.hooks.preprocess_exclude_path_format'
    # 'PREPROCESSING_HOOKS': [],

    # # enum name overrides. dict with keys "YourEnum" and their choice values "field.choices"
    # 'ENUM_NAME_OVERRIDES': {},
    # # Adds "blank" and "null" enum choices where appropriate. disable on client generation issues
    # 'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': True,

    # # function that returns a list of all classes that should be excluded from doc string extraction
    # 'GET_LIB_DOC_EXCLUDES': 'drf_spectacular.plumbing.get_lib_doc_excludes',

    # # Function that returns a mocked request for view processing. For CLI usage
    # # original_request will be None.
    # # interface: request = build_mock_request(method, path, view, original_request, **kwargs)
    # 'GET_MOCK_REQUEST': 'drf_spectacular.plumbing.build_mock_request',

    # # Camelize names like operationId and path parameter names
    # 'CAMELIZE_NAMES': False,

    # # Determines if and how free-form 'additionalProperties' should be emitted in the schema. Some
    # # code generator targets are sensitive to this. None disables generic 'additionalProperties'.
    # # allowed values are 'dict', 'bool', None
    # 'GENERIC_ADDITIONAL_PROPERTIES': 'dict',

    # # Determines whether operation parameters should be sorted alphanumerically or just in
    # # the order they arrived. Accepts either True, False, or a callable for sort's key arg.
    # 'SORT_OPERATION_PARAMETERS': True,

    # # Option for turning off error and warn messages
    # 'DISABLE_ERRORS_AND_WARNINGS': False,

    # # General schema metadata. Refer to spec for valid inputs
    # # https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#openapi-object
    # 'TITLE': '',
    # 'DESCRIPTION': '',
    # 'TOS': None,
    # # Optional: MAY contain "name", "url", "email"
    # 'CONTACT': {},
    # # Optional: MUST contain "name", MAY contain URL
    # 'LICENSE': {},
    # # Statically set schema version. May also be an empty string. When used together with
    # # view versioning, will become '0.0.0 (v2)' for 'v2' versioned requests.
    # # Set VERSION to None if only the request version should be rendered.
    'VERSION': '0.0.1',
    # # Optional list of servers.
    # # Each entry MUST contain "url", MAY contain "description", "variables"
    'SERVERS': [{"url": 'http://localhost'}],
    # # Tags defined in the global scope
    # 'TAGS': [],
    # # Optional: MUST contain 'url', may contain "description"
    # 'EXTERNAL_DOCS': {},

    # # Arbitrary specification extensions attached to the schema's info object.
    # # https://swagger.io/specification/#specification-extensions
    # 'EXTENSIONS_INFO': {},

    # # Oauth2 related settings. used for example by django-oauth2-toolkit.
    # # https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#oauth-flows-object
    # 'OAUTH2_FLOWS': [],
    # 'OAUTH2_AUTHORIZATION_URL': None,
    # 'OAUTH2_TOKEN_URL': None,
    # 'OAUTH2_REFRESH_URL': None,
    # 'OAUTH2_SCOPES': None,
}
